groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('', views.ListGroupView.as_view(), name='all_groups'),
    path('new/', views.CreateGroupView.as_view(), name='create_group'),
    path('posts/in/<slug>', views.GroupDetailView.as_view(), name='group_detail'),
    path('join/<slug>/', views.JoinGroupView.as_view(), name='join_group'),
    path('leave/<slug>/', views.LeaveGroupView.as_view(), name='leave_group'),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.GroupPostListView.as_view(), name='group_post_list'),
    path('new/', views.CreatePostView.as_view(), name='create_post'),
    path('by/<username>/', views.UserPostListView.as_view(), name='user_post_list'),
    path('by/<username>/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete_post'),
]

socialmediasite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls'), name='groups'),
    path('posts/', include('posts.urls'), name='posts'),
    path('welcome/', views.WelcomePage.as_view(), name='welcome'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
from django import template
import misaka


# for 'get_user_groups' in post_list.html
User = get_user_model()
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)  # to get rid of whitespaces etc.
        self.description_html = misaka.html(self.description)  # to get markdown
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:group_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']  # the default ordering for the object, for use when obtaining lists of objects


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    # 'user_groups' for 'get_user_groups' in post_list.html
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from groups.models import Group, GroupMember
from django.shortcuts import get_object_or_404
from django.db import IntegrityError


class CreateGroupView(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group


class GroupDetailView(generic.DetailView):
    model = Group


class ListGroupView(generic.ListView):
    model = Group


class JoinGroupView(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:group_detail', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, f"You are already a member of {group.name} group.")
        else:
            messages.success(self.request, f"You are now a member of the {group.name} group.")

        return super().get(request, *args, **kwargs)


class LeaveGroupView(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:group_detail', kwargs={'slug': self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, f"You are not a member of {group.name} group.")
        else:
            membership.delete()
            messages.success(self.request, f"You have left the {group.name} group.")

        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

  <div class="container">
    <div class="row">

      {% block pregroup %}
      {% endblock %}

      {% block group_content %}
      {% endblock %}

      {% block postgroup %}
      {% endblock %}

    </div>
  </div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

  <div class="container">
  {#  lowercase 'model' from GroupDetailView class#}
    <h1><strong>{{ group.name }}</strong></h1>
    <h5>members: {{ group.members.count }}</h5>

    <div class="content">
      {% if user in group.members.all %}

        <a href="{% url 'groups:leave_group' slug=group.slug %}" class="btn btn-lg btn-warning">
          <span class="fa fa-times-circle-o">Leave</span>
        </a>

      {% else %}

        <a href="{% url 'groups:join_group' slug=group.slug %}" class="btn btn-lg btn-warning">
          <span class="fa fa-check-circle-o">Join</span>
        </a>

      {% endif %}
    </div>
  </div>

{% endblock %}


{% block group_content %}

  {#to avoid displaying on the entire page#}
  <div class="col-md-8 postslist">
    {% if group.posts.count == 0 %}
      <h5>No posts in this group yet.</h5>
    {% else %}
      {% for post in group.posts.all %}
        {% include 'posts/_post.html' %}
      {% endfor %}
    {% endif %}
  </div>

{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block group_content %}
  <h4>Create a new group:</h4>
  <form action="{% url 'groups:create_group' %}" method="post" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary btn-large">Create</button>
  </form>

{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

  <div class="col-md-4">

    <div class="content">
      {% if user.is_authenticated %}
      <h2>
        Welcome back
        <a href="{% url 'posts:user_post_list' username=user.username %}">@{{ user.username }}</a>
      </h2>
      {% endif %}
      <h2>Groups</h2>
    </div>

    {% if user.is_authenticated %}
      <a href="{% url 'groups:create_group' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Create a group</a>
    {% endif %}

  </div>

{% endblock %}

{% block group_content %}

  <div class="col-md-8">

    <div class="list-group">
      {% for group in object_list %}
      <a href="{% url 'groups:group_detail' slug=group.slug %}"
          class="list-group-item list-group-item-action flex-column align-items-start">
        <h3 class="mb-1">{{ group.name }}</h3>
        <p class="mb-1">{{ group.description_html|safe }}</p>
        <div class="d-flex w-40 justify-content-between">
          <small class="text-muted"><span class="badge badge-secondary">
            {{ group.members.count }}</span> member{{ group.members.count | pluralize }}</small>
          <small class="text-muted"><span class="badge badge-secondary">
            {{ group.posts.count }}</span> post{{ group.posts.count | pluralize }}</small>
        <span></span><span></span>
        </div>
      </a>
      {% endfor %}
    </div>

  </div>

{% endblock %}