accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('', views.ListGroupView.as_view(), name='all_groups'),
    path('new/', views.CreateGroupView.as_view(), name='create_group'),
    path('posts/in/<slug>', views.GroupDetailView.as_view(), name='group_detail'),
    path('join/<slug>/', views.JoinGroupView.as_view(), name='join_group'),
    path('leave/<slug>/', views.LeaveGroupView.as_view(), name='leave_group'),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.GroupPostListView.as_view(), name='group_post_list'),
    path('new/', views.CreatePostView.as_view(), name='create_post'),
    path('by/<username>/', views.UserPostListView.as_view(), name='user_post_list'),
    path('by/<username>/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete_post'),
]

socialmediasite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls'), name='groups'),
    path('posts/', include('posts.urls'), name='posts'),
    path('welcome/', views.WelcomePage.as_view(), name='welcome'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>StarSocial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'socialmediasite/css/master.css'%}">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">StarSocial</a>
        </div>
        <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'posts:create_post' %}" class="btn btn-simple">Post</a>
                <a class="nav-item nav-link" href="{% url 'groups:all_groups' %}" class="btn btn-simple">Groups</a>
                <a class="nav-item nav-link" href="{% url 'groups:create_group' %}" class="btn btn-simple">Create a group</a>
                <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'groups:all_groups' %}" class="btn btn-simple">Groups</a>
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
            {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mycontent">
        {% block content %}

        {% endblock %}
    </div>

</body>

    <canvas id="canvas"></canvas>
    <script src="{% static "socialmediasite/js/master.js" %}" type="text/javascript" ></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>StarSocial</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
    <h1>You are now logged in.</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
    <h1>Thanks for visiting StarSocial. Come back soon!</h1>
{% endblock %}

templates/welcome.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome! You are now logged in.</h1>
{% endblock %}