groups/urls.py
from django.urls import path
from . import views


app_name = 'groups'

urlpatterns = [
    path('', views.ListGroupView.as_view(), name='all_groups'),
    path('new/', views.CreateGroupView.as_view(), name='create_group'),
    path('posts/in/<slug>', views.GroupDetailView.as_view(), name='group_detail'),
    path('join/<slug>/', views.JoinGroupView.as_view(), name='join_group'),
    path('leave/<slug>/', views.LeaveGroupView.as_view(), name='leave_group'),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.GroupPostListView.as_view(), name='group_post_list'),
    path('new/', views.CreatePostView.as_view(), name='create_post'),
    path('by/<username>/', views.UserPostListView.as_view(), name='user_post_list'),
    path('by/<username>/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete_post'),
]

socialmediasite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('groups/', include('groups.urls'), name='groups'),
    path('posts/', include('posts.urls'), name='posts'),
    path('welcome/', views.WelcomePage.as_view(), name='welcome'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
import misaka
from groups.models import Group


User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    text = models.TextField()
    text_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        self.text_html = misaka.html(self.text)  # to get markdown
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'username': self.user.username,
                                                    'pk': self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ('user', 'text')

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from django.contrib.auth import get_user_model
from braces.views import SelectRelatedMixin
from . import models

User = get_user_model()


class GroupPostListView(SelectRelatedMixin, generic.ListView):  # posts of the group
    model = models.Post
    select_related = ('user', 'group')


class UserPostListView(generic.ListView):  # posts of the user
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username"))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user  # used in user_post_list.html
        return context


class PostDetailView(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePostView(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('text', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user  # connecting the user with the post
        self.object.save()
        return super().form_valid(form)


class DeletePostView(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:group_post_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post deleted.')
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="media">
	<h3 class="mr-5"><a href="{% url 'posts:user_post_list' username=post.user.username %}">@{{ post.user.username }}</a></h3>

	<div class="media-body">
		<h5>{{ post.text_html | safe }}</h5>
    <p>
			<time class="time"><a href="{% url 'posts:post_detail' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in <a href="{% url 'groups:group_detail' slug=post.group.slug %}">{{ post.group.name }}</a></span>
			{% endif %}
    </p>


		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete_post' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="fa fa-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      {% block prepost %}
      {% endblock %}

      {% block post_content %}
      {% endblock %}

      {% block postpost %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
  <h3>Are you sure you want to delete this post?</h3>

  <div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True %}
  </div>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-large">Delete</button>
    <a href="{% url 'posts:post_detail' username=user.username pk=object.pk %}"
       class="btn btn-light btn-large">Cancel</a>
  </form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<!-- <div class="col-md-8"> -->
    {% include "posts/_post.html" %}
<!-- </div> -->
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
  <h4>New post</h4>
  <form id="postForm" action="{% url 'posts:create_post' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary btn-large">Post</button>
    {% endbuttons %}
  </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}

  <div class="col-md-4">
    {% if request.user.is_authenticated %}
      <div class="card card-with-shadow">
        <div class="content">
          <h5 class="title">Your groups</h5>
          <ul class="list-unstyled">
{#          'get_user_groups' from 'user''s 'related_name' 'user_groups' in GroupMember #}
            {% for group_member in get_user_groups %}
              <li class="group li-with_bullet">
                <a href="{% url 'groups:group_detail' slug=group_member.group.slug %}"></a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    {% endif %}

    <div class="card card-with_shadow">
      <div class="content">
        <h5 class="title">All groups</h5>
        <ul class="list-unstyled">
          {% for other_group in get_other_groups %}
            <li class="group li-with-bullet">
              <a href="{% url 'groups:group_detail' slug=other_group.slug %}"></a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

{% endblock %}


{% block post_content %}

  <div class="col-md-8">
    {% for post in post_list %}
      {% include 'posts/_post.html' %}
    {% endfor %}
  </div>

{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
  <div class="col-md-4">
    <h1>@{{ post_user.username }}</h1>
  </div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include 'posts/_post.html' %}
    {% endfor %}
  </div>
{% endblock %}